### PR TITLE
fix typo compiller => compiler

### PR DESCRIPTION
**Pull request by yutosasaki**
Hi! Fix some typos

compiller => compiler
compille => compile

### CODE REVIEW

**Comment by Ybalrid** [comment]
Effectivement

**Comment by Ybalrid** [comment]
Jut by curiosity, your profile says you're from Japan. You speak French? ^^"

**Comment by yutosasaki** [comment]
Thank you for the response.
I can't speak French...
I want to go to Paris:) It’s a beautiful city.

**Comment by Ybalrid** [comment]
^^"

If you are starting with Ogre, you probably want to check the official Wiki for tutorials. They have some beginer stuff and a whole "application framework" that will take care of the ugly stuff for you. 

I'm French living near Paris. 
The center, "historic" part of the city is great. The rest of it, less so... 
But, If you like museums and parks and monuments and small corner-street _cafés_, well it's Paris! ;-)

**Comment by yutosasaki** [comment]
Thank you very much for giving me many advice.

In Japan, the cherry blossoms are in full bloom. People gather under blooming cherry trees to hold a party. It's called "HANAMI" in Japan.

Please come and hang out in Japan :)

**Comment by Ybalrid** [comment]
Cherry trees here are alson in "All pink/white flowers" mode here ;-)

And definitively, I would like to go to Japan someday. I can't do this in the near future, but Japan is well ranked in my list of "places to visit" :-P

If you want to discuss on something a bit more practical than GitHub's issue system, you can send me mail at this address: ybalrid@cecmu.org 

See ya!

**Pull request merged**
